---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    # hostname: sonarr.lan
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=nc.innofox.com
      - VIRTUAL_PATH=/sonarr/
      - VIRTUAL_PORT=80
    volumes:
      - ./config/:/config
      - /mnt/data/Media/TV Shows/:/tv
      - /mnt/data/Downloads/complete/:/downloads
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
