version: '3.8'

services:
  proxy:
    build: ./proxy
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
networks:
  default:
    external:
      name: nginx-proxy
