version: "3"
services:
  db_recipes:
    container_name: recipes_db
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    container_name: recipes_web
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

  nginx_recipes:
    container_name: recipes_nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 83:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media
    networks:
      macvlan0:
          ipv4_address: 192.168.1.83
      default:

volumes:
  nginx_config:
  staticfiles:

networks:
    default:
    macvlan0:
        external: yes
