version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=changeme
      - PLEX_UID=1002
      - PLEX_GID=1002
      - VIRTUAL_HOST=plex.lan
      - VIRTUAL_PORT=32400
      - ADVERTISE_IP="http://192.168.1.2:80/"
    hostname: plex.lan
    volumes:
      - /mnt/data/Media/.plexconfig:/config
      - ./transcode:/transcode
      - /mnt/data/Media/:/data
    devices:
      - "/dev/dri/card0:/dev/dri"

networks:
  default:
    external:
      name: nginx-proxy
