---
version: "2.1"
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    hostname: sabnzbd.lan
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
      - VIRTUAL_HOST=sabnzbd.lan
      - VIRTUAL_PORT=8080
    volumes:
      - ./config/:/config
      - /mnt/data/Downloads/complete:/downloads
      - /mnt/data/Downloads/incomplete:/incomplete-downloads #optional
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
