---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr.lan
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - VIRTUAL_HOST=radarr.lan
      - VIRTUAL_PORT=80
    volumes:
      - ./config/:/config
      - /mnt/data/Media/Movies:/movies
      - /mnt/data/Downloads/complete:/downloads
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
