---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=192.168.1.2
    volumes:
      - ./config:/config
      - /mnt/data/Media/TV Shows/:/data/tvshows
      - /mnt/data/Media/Movies/:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy
