---
version: "2.1"
services:
    munin:
        container_name: munin
        image: occitech/munin
        restart: unless-stopped
        environment:
            - TZ=Europe/London
            - DISABLELOCALNODE=yes
            - CRONDELAY=1
            - 'NODES=server.lan:192.168.1.2 octopi.lan:192.168.1.4'
        volumes:
            - 'db:/var/lib/munin'
            - 'logs:/var/log/munin'
            - 'cache:/var/cache/munin'
        networks:
            macvlan0:
                ipv4_address: 192.168.1.84

volumes:
    db:
    logs:
    cache:

networks:
    macvlan0:
        external: true

